name: ecommerce
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0-152.0.dev <4.0.0'





dependencies:
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.15.4
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  persistent_bottom_nav_bar_v2: ^4.2.8
  provider: ^6.1.1

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true


  assets:
    - assets/images/

flutter_assets:
  assets_path: assets/images/
  output_path: lib/utilities/assets.dart
  filename: assets.dart
  field_prefix: null
