// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHiHDT4_1nyqzAHE53vOFfqwMZRObar1w',
    appId: '1:566321836051:web:8a5cb550bcc87851b28fe6',
    messagingSenderId: '566321836051',
    projectId: 'ecommerce-for-ex',
    authDomain: 'ecommerce-for-ex.firebaseapp.com',
    storageBucket: 'ecommerce-for-ex.appspot.com',
    measurementId: 'G-GXXDFTEWKZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZgMpWSo-x7R-I03nax-8VaupOiWVUGas',
    appId: '1:566321836051:android:5cad411fcda8df0eb28fe6',
    messagingSenderId: '566321836051',
    projectId: 'ecommerce-for-ex',
    storageBucket: 'ecommerce-for-ex.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8fNn90MM1lcqFkEGkfr43QHItOqBRfxA',
    appId: '1:566321836051:ios:49f15c07af44b19bb28fe6',
    messagingSenderId: '566321836051',
    projectId: 'ecommerce-for-ex',
    storageBucket: 'ecommerce-for-ex.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8fNn90MM1lcqFkEGkfr43QHItOqBRfxA',
    appId: '1:566321836051:ios:7dc0959a01c78bf8b28fe6',
    messagingSenderId: '566321836051',
    projectId: 'ecommerce-for-ex',
    storageBucket: 'ecommerce-for-ex.appspot.com',
    iosBundleId: 'com.example.ecommerce.RunnerTests',
  );
}
