// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoRMQrsFWY6GTcTNb-RQ3u01p-dU2RvlQ',
    appId: '1:78485849218:web:918950920557a90891a09b',
    messagingSenderId: '78485849218',
    projectId: 'ecommerce-5e236',
    authDomain: 'ecommerce-5e236.firebaseapp.com',
    storageBucket: 'ecommerce-5e236.appspot.com',
    measurementId: 'G-PCDSK0HYCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5Uyh1LSH7M2217bVXpNwyLR_Xp5imhxo',
    appId: '1:78485849218:android:6e62b456428b04fe91a09b',
    messagingSenderId: '78485849218',
    projectId: 'ecommerce-5e236',
    storageBucket: 'ecommerce-5e236.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCScFULXKDRerqAhp4gS4VV2wldh3qstBw',
    appId: '1:78485849218:ios:62a2e7c0934b760191a09b',
    messagingSenderId: '78485849218',
    projectId: 'ecommerce-5e236',
    storageBucket: 'ecommerce-5e236.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCScFULXKDRerqAhp4gS4VV2wldh3qstBw',
    appId: '1:78485849218:ios:09f7b1e3c6f2203791a09b',
    messagingSenderId: '78485849218',
    projectId: 'ecommerce-5e236',
    storageBucket: 'ecommerce-5e236.appspot.com',
    iosBundleId: 'com.example.ecommerce.RunnerTests',
  );
}
